GET http://localhost:3001/api/notes

###POST
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "id": 4,
  "content": "On a hill far away stood an old rugged cross",
  "date": "2023-07-28T17:30:31.098Z",
  "important": true
}