GET http://localhost:3001/api/notes

###POST
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "where the dearest and the best",
  "date": "2023-07-28T17:30:31.098Z",
  "important": true
}